# Generated by Django 5.2.1 on 2025-05-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Finance', 'Finance'), ('Hostel', 'Hostel'), ('Mess', 'Mess'), ('Academics', 'Academics'), ('Others', 'Others')], max_length=50)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='attachments/')),
                ('ticket_id', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
    ]
