# Generated by Django 5.2.1 on 2025-05-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
