# Generated by Django 5.2.1 on 2025-05-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Hostel', 'Hostel'), ('Gatepass', 'Gatepass'), ('Academics', 'Academics'), ('Others', 'Others')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
