# Generated by Django 5.2.1 on 2025-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_ticket_escalated_at_ticket_escalated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
    ]
