# Generated by Django 5.2.1 on 2025-06-10 06:22

import Student.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_ticket_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slaconfig',
            options={'verbose_name': 'SLA Configuration', 'verbose_name_plural': 'SLA Configurations'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='escalation_time_hours',
            field=models.IntegerField(default=24, help_text='Time in hours after which the ticket should be escalated'),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='resolution_time_hours',
            field=models.IntegerField(default=24, help_text='Maximum time in hours to resolve the ticket'),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='response_time_hours',
            field=models.IntegerField(default=8, help_text='Maximum time in hours to first response'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png']), Student.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
