# Generated by Django 5.2.1 on 2025-05-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_default_departments'),
        ('core', '0002_create_departments'),
    ]

    operations = [
    ]
