# Generated by Django 5.2.1 on 2025-06-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initialize_departments'),
        ('core', '0003_merge_20250531_0432'),
        ('core', '0005_cleanup_duplicate_departments'),
    ]

    operations = [
    ]
