# Generated by Django 5.2.1 on 2025-06-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sla_hours',
            field=models.IntegerField(default=48),
        ),
    ]
