# Generated by Django 5.2.1 on 2025-05-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
